---
title: "Assignment - Working with XML and JSON in R"
author: "Mary Anna Kivenson"
date: "3/16/2019"
output:
  html_document:
    highlight: pygments
    theme: united
    toc: yes
    toc_float: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r packages, message=FALSE, warning=FALSE}
library(XML) #for readHTMLTable, xmlTreeParse, and xmlSApply
library(RCurl) #for getURL function
library(rjson) #for fromJSON function
library(DT) #for datatables
library(tidyr) #for data wrangling
library(dplyr) #for data wrangling
library(magrittr) #for data wrangling
```

## HTML  {.tabset .tabset-fade}

### Import
```{r html, message=FALSE, warning=FALSE}
books_html <- as.data.frame(readHTMLTable(getURL("https://raw.githubusercontent.com/mkivenson/Data-Acquisition-and-Management/master/Assignment%205/books.html"), header = TRUE))
datatable(books_html)
```

### Tidy
```{r html_long, message=FALSE, warning=FALSE}
books_html %<>%
  separate(books.author,c("author1","author2","author3","author4"), sep = ",") %>%
  gather("id","author",2:5) %>%
  na.omit()  %>%
  arrange(books.title)
datatable(books_html)
```

## XML  {.tabset .tabset-fade}

### Import
```{r xml, warning=FALSE}
books_xml <- xmlTreeParse(getURL("https://raw.githubusercontent.com/mkivenson/Data-Acquisition-and-Management/master/Assignment%205/books.xml"))
books_xml <- xmlSApply(books_xml,function(x) xmlSApply(x, xmlValue))
books_xml <- data.frame(t(books_xml), row.names=NULL)
datatable(books_xml)
```

### Tidy
```{r xml_long, message=FALSE, warning=FALSE}
books_xml %<>%
  separate(author,c("author1","author2","author3","author4"), sep = ",") %>%
  gather("id","author",2:5) %>%
  na.omit() %>%
  arrange(title)
datatable(books_xml)
```


## JSON

### Import

```{r json, warning=FALSE}
books_json <- fromJSON(file = "books.json")
books_json <- as.data.frame(books_json)
datatable(books_json)
```



## Takeaway

The HTML, XML, and JSON formats are nearly identical once imported into R. The main distinction is that the json format allowed the multiple authors to be entered as a vector, so the fromJSON function imported the data in long format. 